version: '3.5'

networks:
  communicator:
    external: false

services:

  pg-communicator-localhost:
    image: "postgres:14.2"
    container_name: pg-communicator-localhost
    ports:
      - "5418:5432"
    environment:
      - POSTGRES_USER=communicator
      - POSTGRES_PASSWORD=communicator
      - POSTGRES_DB=communicator
      - DEBUG=True
    restart: always
    networks:
      - communicator

  redis-communicator-localhost:
    image: "redis:latest"
    container_name: redis-communicator-localhost
    ports:
      - 6379:6379
    networks:
      - communicator