# Generated by Django 4.1.5 on 2023-01-28 06:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True)),
                ('hash_id', models.CharField(max_length=60, null=True)),
                ('long_url', models.CharField(max_length=250)),
                ('short_url', models.CharField(max_length=60, null=True)),
                ('times_clicked', models.IntegerField(default=0)),
                ('type_url', models.CharField(choices=[('GENERIC', 'Generico'), ('UNIQUE', 'unico')], max_length=8)),
                ('active', models.BooleanField(default=True)),
                ('expiration_date', models.DateField()),
            ],
            options={
                'verbose_name': 'short_url',
                'verbose_name_plural': 'short_urls',
                'db_table': 'short_url',
                'unique_together': {('id',)},
            },
        ),
    ]
